version: "~> 1.0"
git:
    depth: 1
    quiet: true
language: java
jdk:
    - openjdk21
branches:
    only:
        - develop
        - support/4.1
cache:
    directories:
        - "$HOME/.m2"
notifications:
    slack: craftersoftware:7YiSb41ZG5rfMgiAY7Qgprc7
before_install:
    - mkdir -p $HOME/.m2
    - cp .travis-settings.xml $HOME/.m2/settings.xml
install: skip
script:
    - if [[ "$TRAVIS_PULL_REQUEST" == "false" ]]; then bash -c "mvn deploy --settings .travis-settings.xml"; fi
    - if [[ "$TRAVIS_PULL_REQUEST" != "false" ]]; then bash -c "mvn clean install"; fi
env:
    global:
        -   secure: "hG0dbQkpqtwqyrDLbD1mEgFhowCZtaV4MpjWOVOkGs6OPQbFDI4NOrzhQwTjryyCRWPFryWwThAS+x1PS7seb2gGJJbbkPtqmDHvm3lLtwz3vKm4XdHufMe6pqmSUHigGgKAB2mFLjV6SXsOgAZlYgZkEp5cIJhIyMHWI/SvdJE3s2CaOrPs2BaXK/h/LrwHgekuK7zuCvjbwSI0uvEImfKc3YZozfw1QstlOfDWIC+Dg42/yCZ2WW+m58/2hPAvPzyAAlpTyoy2yWK53QiaWvbTUai1YGPSoFonsNKymC5kpUfjWVwFR8ZauEQEge4IinCkxXQtBcX/TGpmAsc9IiKWp/GpMv49npsoJj9RjrC/UtPNwb08GKtdN4z66QaUv+iiPP8/+f90Cg9wmHH+PprsaNO0RtUcxB+0eOXY6BQ8shV9OwFVp0JAOklZu+Ru2GPd4ieRq69I8TBK+iFc955xlBMxh9k8VpbWjpGDGOJzkCuTZR6LOdcailwKFIQj+TZ/UHukYcVcPdISkoRPrIiMKc6Jdbsxrf6n2puM0OaMgodK5ytQn1AQa5JMDDF0hOaEly2AB689pdg8izLSc9/h/IgDINeMePQfpTWwUW9YgdxZsnguuCgd3Q3UTqXaNX2dyadLC4RXIhuDCbKuANFLfGdRECqbusMZHMvy54k="
        -   secure: "YZEn3G1dUh7FuD4JMB0TyfcXZ6trngvMYp0zy2UvlGt72BeIFhr5mQ7bpsthhD8Ymna1ghsFHh1GBEbkflzkhZip7AH/v55UG0p3XZnq4JtPE3LhLcS7YKW1EKmc3tKBzQv3GJ8KR4wtYsDMwnKfzc643wBvsP7Dh09a1R1UmBYkFhUD3JoDWHfe5f6PcQHsTMztW8tU0Zf8ynNfakmDpoNhWWi/gukKyaqf9SHXlJeFMyvCyhNpIqx89ELzyeTkV2AYlAnGAzKnt8BK/aab9ToNXYbmX2td5zWnG19yfnBrLR45yJZSlgEOyzaLdyMoFhW1I1H9p0N35XAS4s3SZyBBMyg1ZdM1D5gayeQV5eMREQlW6FanPoOcz0iTf+G0YMAqV4FDfRdvQQWIEByn+bLXU3qI8RyxcajzQqfEFrU3HXc0uUbQNy+11JUrunN7Vn/QMW6M5FPN7eeJTilpgx1ycLcLypCQt8dtXC03VApDfpUCfIarse8cAzYW8T8U8ccW+qww7Zng/KhiwUFF1pMyUt8kDlNu97nR2oWvMS2VT5ZYZ88GRvYgTdSfN/eP2cqsfCmzWF1Spp/tMsGQDN6dWNLuJ6cUcyPMCS9QyurLjdIkBUoyV5ZwKyes2KgdC11VQKQp4/1WaNm6UhsAIXJ6lcRA5WBvCZ/LT3pKdQc="
