version: "~> 1.0"
git:
    depth: 1
    quiet: true
language: java
jdk:
    - openjdk21
branches:
    only:
        - develop
        - support/4.1
cache:
    directories:
        - "$HOME/.m2"
notifications:
    slack: craftersoftware:7YiSb41ZG5rfMgiAY7Qgprc7
before_install:
    - mkdir -p $HOME/.m2
    - cp .travis-settings.xml $HOME/.m2/settings.xml
install: skip
script:
    - if [[ "$TRAVIS_PULL_REQUEST" == "false" ]]; then bash -c "mvn deploy --settings .travis-settings.xml"; fi
    - if [[ "$TRAVIS_PULL_REQUEST" != "false" ]]; then bash -c "mvn clean install"; fi
env:
    global:
        - secure: "lIfvvn4GFbvKljSLga1KWEuPAPOZfnx16yxwUKnQGzlbwMliQkstwLyaniJrYVUqTcrfk5aOWbJEkk9kxZPsf1Kt5lun8xcN+dXkTXsy88JJYpTxiBNDTjG03NiNL7qJdxWkgqeKDBvZoM41oaDpCrm4dTw5dfQqKjgXHLkKhnfuYi5zeNVjsUpvrv65xEIXX+ZtYrXy89TMb/ElJyml6h9H4q8NrFGZd8TS9o3yLrHKlwelh07Q5NQbkv0ULLQXWoC6hGN3Or1fDtxwZ/U4Sonmv2Dqvf+ubiIFEJCbC2Zshok4Nw5J30TLODqTZ/wIhBj1i7sLxhjIZI6vMt/MY697nPXoxDcKDdpHfTeQXWF565Zfh1hYh04gTmTQVu7een/YfE6jANbyAhSRIHIFG+O/wJaWIe/6U88h0DGQtX2SEaAhvEcUxQf4oUnkJkImCeOZInSbapmkSHXiIkr8HBTHPh7qCVh5Ax4h9nJHqYjAS3UAbMgUCB3A3vblyYLwxFLdywb58dXl2LDBRYOUSsVFH57uZtMRGNHqmHVXOK+C1EGtHETKF/UXdeJrfmd6h6kl88+RLqrzLCoZuqAXqSOXqxSQkD2X6vm0jaDnT8vqBpqkKeXkTySDlUHGtO7GLvLS4MNcnE76hIphyc0FdSF/T89at6PDHxrZIbI5Mfk="
        - secure: "DDjVeiDgLl9SiPmbdbeisJPq9GweJPjlv990thB/+Ko9aUGY28xEoPgYbD235uLP05kI5JjfI1QY7A+impDVxQ+AVMHePGx53NRv2lkhlbNxhbpoafZ7G9/ewEz8RbRO8tKe1cG+bX2GyjoRo20uKd/27eaphVmKrAlbrlR2swHygvxlU4RYtulhiz39s/xCwffHxouT3AL7/lfuWjhIsf63gu2IxZe8FD/Us6FXwuEukKvIqPTcOdW94rddiAar7ElxvU9A7lX4NVcBgVy+ZswLTow3Vj/9dtsNz9IpnubFSiF8inujJLzcEetxXJGbHTcCYo2UQqRCnoSf6S+bI9F7zxE1lTAPiNdtYXpld9gG2y1ACYI9DXr0n34JF/KbXETTjZ+H48yLHmMTXctX4ZcFKrYk4ZkeTi/cLDr0vG5wzZe8xuH1cLr5tU57dKcDpEsebGnYnsmTmQe5ap6c8nuHxK0WUuKupRiBlRzBUbdvFFdDaeBBz+0R6yEOOFXc2Ikowtd/C31WdsPRWIYAcb1/gohYL5kg0lBEB+VmjLNGaNhcnkLD1M/Gr9azCgjINqUH55w0hprvL1EeYsoBxzcBpi8got2KbL+tzBwJoBoSKhKM/PHSBsVN7egcuv33MWVjKNqKZD8ZRtp39H1AS2WUammyK5zBnKYDGrPsRFI="
