version: "~> 1.0"
git:
  depth: 1
  quiet: true
language: java
jdk:
  - openjdk21
branches:
  only:
    - develop
    - support/4.x
cache:
  directories:
    - "$HOME/.m2"
notifications:
  slack: craftersoftware:7YiSb41ZG5rfMgiAY7Qgprc7
before_install:
  - mkdir -p $HOME/.m2
  - cp .travis-settings.xml $HOME/.m2/settings.xml
install: skip
script:
  - if [[ "$TRAVIS_PULL_REQUEST" == "false" ]]; then bash -c "mvn deploy --settings .travis-settings.xml"; fi
  - if [[ "$TRAVIS_PULL_REQUEST" != "false" ]]; then bash -c "mvn clean install"; fi
env:
  global:
   - secure: "KlEXjnnS59MHCtcCpbMZKW4DiTS4seteD9p5X7fWnvrFgj2DvKTVOcRGhVrRx0ppGX1oVfSN4lnh5HMZf0oDMcRbfvy082t+wKdaaoMSTkV5Qd9ZaZB6dgAnIVTg9+cKz02XpP88BE94zbwtjNLw/Gquct+PlflCV00d1E02nTeEjdNZEaaQfVa1T70RLd2reM3rhVME0z4dW96b6jVexpyGVd8Z9uNCLGLp0KHRQGsYicN3JFuGpqazWf9ffuoxfMth9iohhPL0zACSv69Je8m/I51GjYBqKHE2x9kxBCIJobFpjnsWHkB4qhiXD9cJ03icCCPdkFW1RdB0DSJJpZKGwYHjzwRaUFmqEHWq6fzTSj1+DakpJpB+NwTht48vI9bBSgR8Z07xX3Pj0W7ME6INca+I934cIYZ7odMomG5WPQUWWGO8E5l03/8lOtShxdFCPMIIS86AaZSskUpt8zbIBV2QuOhHe9bApi8MdnIEva+5dRBPjEs+PmWykOSvfBIm4M6v17Bze5uw7nMe15C5FyB6ojbVCzXVPO/hkrx0t6WB/PyW8K80qkXCa+tbSV78DB8DBG3hmA+MR8Ww8g7hOC1nJkELX3D+K+ulZQ2+nDQiL1MJECpPcq8YrOMKSHqFwlGN1libeC2t72Oa3XiCuJApNX3HISZPfVzf48M="
   - secure: "iq/YTP18r7U7WMba2Sak0RTzgYVHnuR3LbwVR1PxzKBUZskh7yN/00PCc0VW5/LuoRNkg2+xoiFoSY6ZSQroxqAsQMyR753QZ/CKLFcyR6Dd8LpwphrQ5r76Bxbv+tZsilQuO6QKwVXQGQ6TyPrQUpQWy7sX3tlct9kHRT9N8oo6OEXta4z7giuQ26ZIwtS+louQQk67zQBPzfuAPDshYQU3CQFond0Iqw090CoebiOm5T9jltNvQsLWX+N9IbXsPkNNSJLCA67qaQDbQ7B8XNt3LiAQxVg6OOFoCwaQtG0AMC1TsaG9OAvXSSmYWNUECpzsRmXjF1OdxX+Ryh3BInCXwTxQQVzy2YumSvToW+g1FQ89rIh5zw4b5BaeR9k3QRDaKtmjIIAHdJAF6hK/FAdwUG4ZwQoBk5jXYRUVIxgkTA6HGMg91XKQh4wiaKppWEiJu6CpXmB8QvLy1+goBu0xjy5NXKAM0eNt9zDcWRJ/HNGQ0CIwzTaQ4ptIuW42rY4ElDtZLR4V0qbX1BWGW0Z8pUwtWdevB341+jC2WmXFwWWwGRrMCXlNyvlOn43Wzx8gPwf17caW8cHiQyv9+uF8fUsyQwhTZg++BukNLlxcqUVTK8zKlv1jpQWsLDikAr8A7l4ELqkFTRvl0swrX7OuC+UtFzBtWKmH8vOXT5s="

